remove "field" from group-by dropdown and add tooltips to "form: fiel…
RhoInc/query-overview pull request #20
Opened 2017-05-04 21:09 UTC by samussiah

…d" y-axis tick labels

Closes #16

2017-05-04 22:59 UTC, jwildfire requested changes
Not seeing titles in CAT. Also suggested a few minor coding tweaks.

2017-05-04 22:59 UTC, jwildfire commented on src/chart/onResize.js
> +  if (this.config.y.column === "Form: Field" && this.config.fieldDescription_col)
This isn't giving a title for me. Also, it should probably be: `this.config.y.column === "Form: Field" && (this.config.fieldDescription_col || this.config.formDescription_col)`

2017-05-04 22:59 UTC, jwildfire commented on src/chart/onResize.js
> +  if (this.config.y.column === "Form: Field" && this.config.fieldDescription_col)
Actually - not getting titles in `v1.0.0-dev` branch either, so probably an issue I introduced with the merge.

2017-05-04 22:59 UTC, jwildfire commented on src/chart/onResize.js
> +        field => {
how about something like this? 
```
myFormDescription = this.config.formDescription_col ? datum[this.config.formDescription_col] : "<<none>>"
myFieldDescription = <same idea as above>;
return "Form: "+myFormDescription+"\nField:"+myFieldDescription;
```

2017-05-05 13:23 UTC, samussiah commented
Branch updated.

2017-05-05 14:14 UTC, jwildfire requested changes
I'm still not actually getting any titles when I mouseover the y-axis :(

2017-05-08 15:40 UTC, samussiah commented
The CDN cache hadn't updated.  Should be good to go now @jwildfire .

2017-05-09 01:48 UTC, jwildfire approved these changes

2017-05-09 01:48 UTC, jwildfire commented
Looks good - merging.

2017-05-09 01:51 UTC, merged